### ISSUE TITLE
Opdracht 1.2

### ISSUE THREAD

**Issue by pp-koch** [jenniferslagt/browser-technologies-1920#3]
Goed! Slechts 1 schoonheidsfoutje: je eerste device is geen iPad, zoals in het kopje staat, maar een Android tablet. (Ik was even verward door een Chrome 80 op een iPad). Maar voor de rest met vlag en wimpel geslaagd.

**Comment by jenniferslagt** [comment]
Top! Heb het aangepast ![bitmoji](https://render.bitstrips.com/v2/cpanel/3c97455d-0ce1-4ac8-82a0-601e6d6f6fd2-83c93cc0-d0ae-4742-a59b-b1a0ec5de8e6-v1.png?transparent=1&palette=1&width=246)
